AIRLINES = {
    "1T": {"iata": "1T", "name": "1Time Airline", "country": "South Africa"},
    "Q5": {"iata": "Q5", "name": "40-Mile Air", "country": "United States"},
    "AN": {"iata": "AN", "name": "Ansett Australia", "country": "Australia"},
    "1B": {"iata": "1B", "name": "Abacus International", "country": "Singapore"},
    "W9": {"iata": "W9", "name": "Abelag Aviation", "country": "Belgium"},
    "ZI": {"iata": "ZI", "name": "Aigle Azur", "country": "France"},
    "AQ": {"iata": "AQ", "name": "Aloha Airlines", "country": "United States"},
    "AA": {"iata": "AA", "name": "American Airlines", "country": "United States"},
    "OZ": {"iata": "OZ", "name": "Asiana Airlines", "country": "Republic of Korea"},
    "4K": {"iata": "4K", "name": "Askari Aviation", "country": "Pakistan"},
    "8U": {"iata": "8U", "name": "Afriqiyah Airways", "country": "Libya"},
    "Q9": {"iata": "Q9", "name": "Afrinat International Airlines", "country": "Gambia"},
    "G4": {"iata": "G4", "name": "Allegiant Air", "country": "United States"},
    "K5": {"iata": "K5", "name": "Aban Air", "country": "Iran"},
    "M3": {"iata": "M3", "name": "ABSA - Aerolinhas Brasileiras", "country": "Brazil"},
    "04": {"iata": "04", "name": "Antrak Air", "country": "Ghana"},
    "GB": {"iata": "GB", "name": "Airborne Express", "country": "United States"},
    "8V": {"iata": "8V", "name": "Astral Aviation", "country": "Kenya"},
    "E4": {"iata": "E4", "name": "Aero Asia International", "country": "Pakistan"},
    "YT": {"iata": "YT", "name": "Air Togo", "country": "Togo"},
    "4G": {"iata": "4G", "name": "Advance Leasing Company", "country": "United States"},
    "7A": {"iata": "7A", "name": "Aztec Worldwide Airlines", "country": "United States"},
    "8T": {"iata": "8T", "name": "Air Tindi", "country": "Canadian Territories"},
    "ZY": {"iata": "ZY", "name": "Ada Air", "country": "Albania"},
    "Z7": {"iata": "Z7", "name": "ADC Airlines", "country": "Nigeria"},
    "JP": {"iata": "JP", "name": "Adria Airways", "country": "Slovenia"},
    "UX": {"iata": "UX", "name": "Air Europa", "country": "Spain"},
    "EM": {"iata": "EM", "name": "Aero Benin", "country": "Benin"},
    "A3": {"iata": "A3", "name": "Aegean Airlines", "country": "Greece"},
    "0C": {"iata": "0C", "name": "Aerofumigaciones Sam", "country": "Chile"},
    "KI": {"iata": "KI", "name": "Air Atlantique", "country": "United Kingdom"},
    "PE": {"iata": "PE", "name": "Air Europe", "country": "Italy"},
    "KO": {"iata": "KO", "name": "Alaska Central Express", "country": "United States"},
    "5W": {"iata": "5W", "name": "Astraeus", "country": "United Kingdom"},
    "VV": {"iata": "VV", "name": "Aerosvit Airlines", "country": "Ukraine"},
    "I9": {"iata": "I9", "name": "Air Italy", "country": "Italy"},
    "WK": {"iata": "WK", "name": "American Falcon", "country": "Argentina"},
    "QQ": {"iata": "QQ", "name": "Alliance Airlines", "country": "Australia"},
    "FG": {"iata": "FG", "name": "Ariana Afghan Airlines", "country": "Afghanistan"},
    "SU": {"iata": "SU", "name": "Aeroflot Russian Airlines", "country": "Russia"},
    "JA": {"iata": "JA", "name": "Air Bosna", "country": "Bosnia and Herzegovina"},
    "AF": {"iata": "AF", "name": "Air France", "country": "France"},
    "SB": {"iata": "SB", "name": "Air Caledonie International", "country": "France"},
    "GN": {"iata": "GN", "name": "Air Gabon", "country": "Gabon"},
    "2O": {"iata": "2O", "name": "Air Salone", "country": "Sierra Leone"},
    "2Q": {"iata": "2Q", "name": "Air Cargo Carriers", "country": "United States"},
    "V7": {"iata": "V7", "name": "Air Senegal International", "country": "Senegal"},
    "SW": {"iata": "SW", "name": "Air Namibia", "country": "Namibia"},
    "G8": {"iata": "G8", "name": "Air Service Gabon", "country": "Gabon"},
    "5D": {"iata": "5D", "name": "Aerolitoral", "country": "Mexico"},
    "1A": {"iata": "1A", "name": "Amadeus Global Travel Distribution", "country": "Spain"},
    "7T": {"iata": "7T", "name": "Air Glaciers", "country": "Switzerland"},
    "PL": {"iata": "PL", "name": "Aeroper", "country": "Peru"},
    "8A": {"iata": "8A", "name": "Atlas Blue", "country": "Morocco"},
    "GD": {"iata": "GD", "name": "Air Alpha Greenland", "country": "Denmark"},
    "LD": {"iata": "LD", "name": "Air Hong Kong", "country": "Hong Kong"},
    "HT": {"iata": "HT", "name": "Aeromist-Kharkiv", "country": "Ukraine"},
    "J2": {"iata": "J2", "name": "Azerbaijan Airlines", "country": "Azerbaijan"},
    "U3": {"iata": "U3", "name": "Avies", "country": "Estonia"},
    "AP": {"iata": "AP", "name": "Airbus Industrie", "country": "France"},
    "5A": {"iata": "5A", "name": "Alpine Air Express", "country": "United States"},
    "ED": {"iata": "ED", "name": "Airblue", "country": "Pakistan"},
    "AB": {"iata": "AB", "name": "Air Berlin", "country": "Germany"},
    "AG": {"iata": "AG", "name": "ASL Airlines Ireland", "country": "Ireland"},
    "AI": {"iata": "AI", "name": "Air India Limited", "country": "India"},
    "UK": {"iata" : "UK","imgcode" : "IK","name" : "Air Vistara", "country" : "India"},
    "ZB": {"iata": "ZB", "name": "Air Bourbon", "country": "Reunion"},
    "CC": {"iata": "CC", "name": "Air Atlanta Icelandic", "country": "Iceland"},
    "RB": {"iata": "RB", "name": "Air Srpska", "country": "Bosnia and Herzegovina"},
    "TN": {"iata": "TN", "name": "Air Tahiti Nui", "country": "France"},
    "W4": {"iata": "W4", "name": "Aero Services Executive", "country": "France"},
    "IZ": {"iata": "IZ", "name": "Arkia Israel Airlines", "country": "Israel"},
    "JM": {"iata": "JM", "name": "Air Jamaica", "country": "Jamaica"},
    "S2": {"iata": "S2", "name": "Air Sahara", "country": "India"},
    "KM": {"iata": "KM", "name": "Air Malta", "country": "Malta"},
    "M6": {"iata": "M6", "name": "Amerijet International", "country": "United States"},
    "NQ": {"iata": "NQ", "name": "Air Japan", "country": "Japan"},
    "4A": {"iata": "4A", "name": "Air Kiribati", "country": "Kiribati"},
    "EH": {"iata": "EH", "name": "Air Nippon Network Co. Ltd.", "country": "Japan"},
    "HP": {"iata": "HP", "name": "America West Airlines", "country": "United States"},
    "ZW": {"iata": "ZW", "name": "Air Wisconsin", "country": "United States"},
    "U9": {"iata": "U9", "name": "Tatarstan Airlines", "country": "Russia"},
    "VD": {"iata": "VD", "name": "Air Libert", "country": "France"},
    "TT": {"iata": "TT", "name": "Air Lithuania", "country": "Lithuania"},
    "QM": {"iata": "QM", "name": "Air Malawi", "country": "Malawi"},
    "BM": {"iata": "BM", "name": "Air Sicilia", "country": "Italy"},
    "NX": {"iata": "NX", "name": "Air Macau", "country": "Macao"},
    "ZV": {"iata": "ZV", "name": "Air Midwest", "country": "United States"},
    "HM": {"iata": "HM", "name": "Air Seychelles", "country": "Seychelles"},
    "AM": {"iata": "AM", "name": "AeroMéxico", "country": "Mexico"},
    "NH": {"iata": "NH", "name": "All Nippon Airways", "country": "Japan"},
    "YW": {"iata": "YW", "name": "Air Nostrum", "country": "Spain"},
    "PX": {"iata": "PX", "name": "Air Niugini", "country": "Papua New Guinea"},
    "G9": {"iata": "G9", "name": "Air Arabia", "country": "United Arab Emirates"},
    "AC": {"iata": "AC", "name": "Air Canada", "country": "Canada"},
    "BT": {"iata": "BT", "name": "Air Baltic", "country": "Latvia"},
    "EL": {"iata": "EL", "name": "Air Nippon", "country": "Japan"},
    "TL": {"iata": "TL", "name": "Airnorth", "country": "Australia"},
    "4N": {"iata": "4N", "name": "Air North Charter - Canada", "country": "Canada"},
    "IW": {"iata": "IW", "name": "AOM French Airlines", "country": "France"},
    "NZ": {"iata": "NZ", "name": "Air New Zealand", "country": "New Zealand"},
    "J6": {"iata": "J6", "name": "AVCOM", "country": "Russia"},
    "2D": {"iata": "2D", "name": "Aero VIP", "country": "Argentina"},
    "6V": {"iata": "6V", "name": "Air Vegas", "country": "United States"},
    "XM": {"iata": "XM", "name": "Alitalia Express", "country": "Italy"},
    "OE": {"iata": "OE", "name": "Asia Overnight Express", "country": "Philippines"},
    "GV": {"iata": "GV", "name": "Aero Flight", "country": "Germany"},
    "JW": {"iata": "JW", "name": "Arrow Air", "country": "United States"},
    "W3": {"iata": "W3", "name": "Arik Air", "country": "Nigeria"},
    "2B": {"iata": "2B", "name": "Aerocondor", "country": "Portugal"},
    "4C": {"iata": "4C", "name": "Aires", "country": " S.A."},
    "AR": {"iata": "AR", "name": "Aerolineas Argentinas", "country": "Argentina"},
    "QN": {"iata": "QN", "name": "Air Armenia", "country": "Armenia"},
    "AS": {"iata": "AS", "name": "Alaska Airlines", "country": "ALASKA"},
    "4D": {"iata": "4D", "name": "Air Sinai", "country": "Egypt"},
    "EV": {"iata": "EV", "name": "Atlantic Southeast Airlines", "country": "United States"},
    "OB": {"iata": "OB", "name": "Astrakhan Airlines", "country": "Russia"},
    "TC": {"iata": "TC", "name": "Air Tanzania", "country": "Tanzania"},
    "2J": {"iata": "2J", "name": "Air Burkina", "country": "Burkina Faso"},
    "HC": {"iata": "HC", "name": "Aero-Tropics Air Services", "country": "Australia"},
    "FO": {"iata": "FO", "name": "Airlines Of Tasmania", "country": "Australia"},
    "PJ": {"iata": "PJ", "name": "Air Saint Pierre", "country": "France"},
    "8C": {"iata": "8C", "name": "Air Transport International", "country": "United States"},
    "OS": {"iata": "OS", "name": "Austrian Airlines", "country": "Austria"},
    "IQ": {"iata": "IQ", "name": "Augsburg Airways", "country": "Germany"},
    "RU": {"iata": "RU", "name": "AirBridge Cargo", "country": "Russia"},
    "MO": {"iata": "MO", "name": "Abu Dhabi Amiri Flight", "country": "United Arab Emirates"},
    "5N": {"iata": "5N", "name": "Aeroflot-Nord", "country": "Russia"},
    "GR": {"iata": "GR", "name": "Aurigny Air Services", "country": "United Kingdom"},
    "NO": {"iata": "NO", "name": "Aus-Air", "country": "Australia"},
    "AU": {"iata": "AU", "name": "Austral Lineas Aereas", "country": "Argentina"},
    "AO": {"iata": "AO", "name": "Australian Airlines", "country": "Australia"},
    "AV": {"iata": "AV", "name": "Avianca - Aerovias Nacionales de Colombia", "country": "AVIANCA"},
    "NF": {"iata": "NF", "name": "Air Vanuatu", "country": "Vanuatu"},
    "K8": {"iata": "K8", "name": "Airlink Zambia", "country": "Zambia"},
    "B9": {"iata": "B9", "name": "Air Bangladesh", "country": "Bangladesh"},
    "DR": {"iata": "DR", "name": "Air Mediterranee", "country": "France"},
    "7E": {"iata": "7E", "name": "Aeroline GmbH", "country": "Germany"},
    "6G": {"iata": "6G", "name": "Air Wales", "country": "United Kingdom"},
    "TX": {"iata": "TX", "name": "Air Caraïbes", "country": "France"},
    "IX": {"iata": "IX", "name": "Air India Express", "country": "India"},
    "HJ": {"iata": "HJ", "name": "Asian Express Airlines", "country": "Australia"},
    "XT": {"iata": "XT", "name": "Air Exel", "country": "Netherlands"},
    "AK": {"iata": "AK", "name": "AirAsia", "country": "Malaysia"},
    "3G": {"iata": "3G", "name": "Atlant-Soyuz Airlines", "country": "Russia"},
    "AZ": {"iata": "AZ", "name": "Alitalia", "country": "Italy"},
    "ZE": {"iata": "ZE", "name": "Arcus-Air Logistic", "country": "Germany"},
    "Z8": {"iata": "Z8", "name": "Amaszonas", "country": "Bolivia"},
    "UM": {"iata": "UM", "name": "Air Zimbabwe", "country": "Zimbabwe"},
    "R7": {"iata": "R7", "name": "Aserca Airlines", "country": "Venezuela"},
    "FV": {"iata": "FV", "name": "Rossiya-Russian Airlines", "country": "Russia"},
    "RX": {"iata": "RX", "name": "Aviaexpress", "country": "Hungary"},
    "MQ": {"iata": "MQ", "name": "American Eagle Airlines", "country": "United States"},
    "FF": {"iata": "FF", "name": "Airshop", "country": "Netherlands"},
    "ML": {"iata": "ML", "name": "African Transport Trading and Investment Company", "country": "Sudan"},
    "VU": {"iata": "VU", "name": "Air Ivoire", "country": "Ivory Coast"},
    "BP": {"iata": "BP", "name": "Air Botswana", "country": "Botswana"},
    "GS": {"iata": "GS", "name": "Air Foyle", "country": "United Kingdom"},
    "VT": {"iata": "VT", "name": "Air Tahiti", "country": "French Polynesia"},
    "3N": {"iata": "3N", "name": "Air Urga", "country": "Ukraine"},
    "VL": {"iata": "VL", "name": "Air VIA", "country": "Bulgaria"},
    "FK": {"iata": "FK", "name": "Africa West", "country": "Togo"},
    "G2": {"iata": "G2", "name": "Avirex", "country": "Gabon"},
    "V8": {"iata": "V8", "name": "ATRAN Cargo Airlines", "country": "Russian Federation"},
    "VE": {"iata": "VE", "name": "Avensa", "country": "Venezuela"},
    "V5": {"iata": "V5", "name": "Avolar Aerolineas", "country": "Mexico"},
    "CA": {"iata": "CA", "name": "Air China", "country": "China"},
    "Q6": {"iata": "Q6", "name": "Aero Condor Peru", "country": "Peru"},
    "5F": {"iata": "5F", "name": "Arctic Circle Air Service", "country": "United States"},
    "QC": {"iata": "QC", "name": "Air Corridor", "country": "Mozambique"},
    "NV": {"iata": "NV", "name": "Air Central", "country": "Japan"},
    "CV": {"iata": "CV", "name": "Air Chathams", "country": "New Zealand"},
    "CW": {"iata": "CW", "name": "Air Marshall Islands", "country": "Marshall Islands"},
    "ZA": {"iata": "ZA", "name": "Access Air", "country": "United States"},
    "AH": {"iata": "AH", "name": "Air Algerie", "country": "Algeria"},
    "ER": {"iata": "ER", "name": "Astar Air Cargo", "country": "United States"},
    "HO": {"iata": "HO", "name": "Antinea Airlines", "country": "Algeria"},
    "EN": {"iata": "EN", "name": "Air Dolomiti", "country": "Italy"},
    "D9": {"iata": "D9", "name": "Aeroflot-Don", "country": "Russia"},
    "NM": {"iata": "NM", "name": "Air Madrid", "country": "Spain"},
    "EE": {"iata": "EE", "name": "Aero Airlines", "country": "Estonia"},
    "4F": {"iata": "4F", "name": "Air City", "country": "Germany"},
    "EI": {"iata": "EI", "name": "Aer Lingus", "country": "Ireland"},
    "E8": {"iata": "E8", "name": "Alpi Eagles", "country": "Italy"},
    "KY": {"iata": "KY", "name": "Air S", "country": "Air S"},
    "PC": {"iata": "PC", "name": "Air Fiji", "country": "Fiji"},
    "OF": {"iata": "OF", "name": "Air Finland", "country": "Finland"},
    "FJ": {"iata": "FJ", "name": "Air Pacific", "country": "Fiji"},
    "RC": {"iata": "RC", "name": "Atlantic Airways", "country": "Faroe Islands"},
    "QH": {"iata": "QH", "name": "Air Florida", "country": "United States"},
    "NY": {"iata": "NY", "name": "Air Iceland", "country": "Iceland"},
    "2P": {"iata": "2P", "name": "Air Philippines", "country": "Philippines"},
    "ZX": {"iata": "ZX", "name": "Air Georgian", "country": "Canada"},
    "2U": {"iata": "2U", "name": "Air Guinee Express", "country": "Guinea"},
    "0A": {"iata": "0A", "name": "Amber Air", "country": "Lithuania"},
    "DA": {"iata": "DA", "name": "Air Georgia", "country": "Georgia"},
    "GL": {"iata": "GL", "name": "Air Greenland", "country": "Denmark"},
    "LL": {"iata": "LL", "name": "Allegro", "country": "Mexico"},
    "5Y": {"iata": "5Y", "name": "Atlas Air", "country": "United States"},
    "GG": {"iata": "GG", "name": "Air Guyane", "country": "French Guiana"},
    "H9": {"iata": "H9", "name": "Air D'Ayiti", "country": "Haiti"},
    "IP": {"iata": "IP", "name": "Atyrau Air Ways", "country": "Kazakhstan"},
    "QK": {"iata": "QK", "name": "Air Canada Jazz", "country": "Canada"},
    "KK": {"iata": "KK", "name": "Atlasjet", "country": "Turkey"},
    "JS": {"iata": "JS", "name": "Air Koryo", "country": "Democratic People's Republic of Korea"},
    "KC": {"iata": "KC", "name": "Air Astana", "country": "Kazakhstan"},
    "LV": {"iata": "LV", "name": "Albanian Airlines", "country": "Albania"},
    "D4": {"iata": "D4", "name": "Alidaunia", "country": "Italy"},
    "CD": {"iata": "CD", "name": "Alliance Air", "country": "India"},
    "XL": {"iata": "XL", "name": "Aerolane", "country": "Ecuador"},
    "A6": {"iata": "A6", "name": "Air Alps Aviation", "country": "Austria"},
    "TD": {"iata": "TD", "name": "Atlantis European Airways", "country": "Armenia"},
    "L8": {"iata": "L8", "name": "Air Luxor GB", "country": "Guinea-Bissau"},
    "LK": {"iata": "LK", "name": "Air Luxor", "country": "Portugal"},
    "MK": {"iata": "MK", "name": "Air Mauritius", "country": "Mauritius"},
    "MD": {"iata": "MD", "name": "Air Madagascar", "country": "Madagascar"},
    "9U": {"iata": "9U", "name": "Air Moldova", "country": "Moldova"},
    "M0": {"iata": "M0", "name": "Aero Mongolia", "country": "Mongolia"},
    "A7": {"iata": "A7", "name": "Air Plus Comet", "country": "Spain"},
    "QO": {"iata": "QO", "name": "Aeromexpress", "country": "Mexico"},
    "MR": {"iata": "MR", "name": "Air Mauritanie", "country": "Mauritania"},
    "3S": {"iata": "3S", "name": "Aeroland Airways", "country": "Greece"},
    "8D": {"iata": "8D", "name": "Astair", "country": "Russian Federation"},
    "F4": {"iata": "F4", "name": "Albarka Air", "country": "Nigeria"},
    "AJ": {"iata": "AJ", "name": "Aero Contractors", "country": "Nigeria"},
    "8Y": {"iata": "8Y", "name": "Air Burundi", "country": "Burundi"},
    "OT": {"iata": "OT", "name": "Aeropelican Air Services", "country": "Australia"},
    "AD": {"iata": "AD", "name": "Air Paradise International", "country": "Indonesia"},
    "QD": {"iata": "QD", "name": "Air Class Lineas Aereas", "country": "Uruguay"},
    "QS": {"iata": "QS", "name": "African Safari Airways", "country": "Kenya"},
    "4Y": {"iata": "4Y", "name": "Airbus France", "country": "France"},
    "MC": {"iata": "MC", "name": "Air Mobility Command", "country": "United States"},
    "RE": {"iata": "RE", "name": "Aer Arann", "country": "Ireland"},
    "UU": {"iata": "UU", "name": "Air Austral", "country": "France"},
    "6K": {"iata": "6K", "name": "Asian Spirit", "country": "Philippines"},
    "RK": {"iata": "RK", "name": "Air Afrique", "country": "Ivory Coast"},
    "A5": {"iata": "A5", "name": "Airlinair", "country": "France"},
    "QL": {"iata": "QL", "name": "Aero Lanka", "country": "Sri Lanka"},
    "MV": {"iata": "MV", "name": "Armenian International Airways", "country": "Armenia"},
    "20": {"iata": "20", "name": "Air Salone", "country": "Sierra Leone"},
    "U8": {"iata": "U8", "name": "Armavia", "country": "Armenia"},
    "BQ": {"iata": "BQ", "name": "Aeromar", "country": "Dominican Republic"},
    "P5": {"iata": "P5", "name": "AeroRep", "country": "Colombia"},
    "BF": {"iata": "BF", "name": "Aero-Service", "country": "Republic of the Congo"},
    "5L": {"iata": "5L", "name": "Aerosur", "country": "Bolivia"},
    "EX": {"iata": "EX", "name": "Air Santo Domingo", "country": "Dominican Republic"},
    "JR": {"iata": "JR", "name": "Aero California", "country": "Mexico"},
    "Z3": {"iata": "Z3", "name": "Avient Aviation", "country": "Zimbabwe"},
    "GM": {"iata": "GM", "name": "Air Slovakia", "country": "Slovakia"},
    "R3": {"iata": "R3", "name": "Aircompany Yakutia", "country": "Russia"},
    "VW": {"iata": "VW", "name": "Aeromar", "country": "Mexico"},
    "JY": {"iata": "JY", "name": "Air Turks and Caicos", "country": "Turks and Caicos Islands"},
    "OR": {"iata": "OR", "name": "Arkefly", "country": "Netherlands"},
    "CG": {"iata": "CG", "name": "Airlines PNG", "country": "Papua New Guinea"},
    "TY": {"iata": "TY", "name": "Air Cal", "country": "France"},
    "FL": {"iata": "FL", "name": "AirTran Airways", "country": "United States"},
    "TS": {"iata": "TS", "name": "Air Transat", "country": "Canada"},
    "EC": {"iata": "EC", "name": "Avialeasing Aviation Company", "country": "Uzbekistan"},
    "VO": {"iata": "VO", "name": "Tyrolean Airways", "country": "Austria"},
    "DW": {"iata": "DW", "name": "Aero-Charter Ukraine", "country": "Ukraine"},
    "6U": {"iata": "6U", "name": "Air Ukraine", "country": "Ukraine"},
    "2K": {"iata": "2K", "name": "Aerolineas Galapagos (Aerogal)", "country": "Ecuador"},
    "6R": {"iata": "6R", "name": "Alrosa Mirny Air Enterprise", "country": "Russia"},
    "8Q": {"iata": "8Q", "name": "Baker Aviation", "country": "United States"},
    "BA": {"iata": "BA", "name": "British Airways", "country": "United Kingdom"},
    "BG": {"iata": "BG", "name": "Biman Bangladesh Airlines", "country": "Bangladesh"},
    "B4": {"iata": "B4", "name": "BACH Flugbetriebsges", "country": "Austria"},
    "BZ": {"iata": "BZ", "name": "Blue Dart Aviation", "country": "India"},
    "J4": {"iata": "J4", "name": "Buffalo Airways", "country": "Canada"},
    "A8": {"iata": "A8", "name": "Benin Golf Air", "country": "Benin"},
    "4T": {"iata": "4T", "name": "Belair Airlines", "country": "Switzerland"},
    "UP": {"iata": "UP", "name": "Bahamasair", "country": "Bahamas"},
    "E6": {"iata": "E6", "name": "Bringer Air Cargo Taxi Aereo", "country": "Brazil"},
    "LZ": {"iata": "LZ", "name": "Balkan Bulgarian Airlines", "country": ""},
    "TH": {"iata": "TH", "name": "BA Connect", "country": "United Kingdom"},
    "BS": {"iata": "BS", "name": "British International Helicopters", "country": "United Kingdom"},
    "PG": {"iata": "PG", "name": "Bangkok Airways", "country": "Thailand"},
    "KF": {"iata": "KF", "name": "Blue1", "country": "Finland"},
    "JV": {"iata": "JV", "name": "Bearskin Lake Air Service", "country": "Canada"},
    "B3": {"iata": "B3", "name": "Bellview Airlines", "country": "Nigeria"},
    "BD": {"iata": "BD", "name": "bmi", "country": "United Kingdom"},
    "WW": {"iata": "WW", "name": "bmibaby", "country": "United Kingdom"},
    "CH": {"iata": "CH", "name": "Bemidji Airlines", "country": "United States"},
    "5Z": {"iata": "5Z", "name": "Bismillah Airlines", "country": "Bangladesh"},
    "BO": {"iata": "BO", "name": "Bouraq Indonesia Airlines", "country": "Indonesia"},
    "BV": {"iata": "BV", "name": "Blue Panorama Airlines", "country": "Italy"},
    "7R": {"iata": "7R", "name": "BRA-Transportes Aereos", "country": "Brazil"},
    "8E": {"iata": "8E", "name": "Bering Air", "country": "United States"},
    "B2": {"iata": "B2", "name": "Belavia Belarusian Airlines", "country": "Belarus"},
    "K6": {"iata": "K6", "name": "Bravo Air Congo", "country": "Democratic Republic of the Congo"},
    "BN": {"iata": "BN", "name": "Braniff International Airways", "country": "United States"},
    "GQ": {"iata": "GQ", "name": "Big Sky Airlines", "country": "United States"},
    "V9": {"iata": "V9", "name": "BAL Bashkirian Airlines", "country": "Russia"},
    "7P": {"iata": "7P", "name": "Metro Batavia", "country": "Indonesia"},
    "J8": {"iata": "J8", "name": "Berjaya Air", "country": "Malaysia"},
    "QW": {"iata": "QW", "name": "Blue Wings", "country": "Germany"},
    "8W": {"iata": "8W", "name": "BAX Global", "country": ""},
    "DB": {"iata": "DB", "name": "Brit Air", "country": "France"},
    "E9": {"iata": "E9", "name": "Boston-Maine Airways", "country": "United States"},
    "SN": {"iata": "SN", "name": "Brussels Airlines", "country": "Belgium"},
    "NT": {"iata": "NT", "name": "Binter Canarias", "country": "Spain"},
    "0B": {"iata": "0B", "name": "Blue Air", "country": "Romania"},
    "KJ": {"iata": "KJ", "name": "British Mediterranean Airways", "country": "United Kingdom"},
    "FB": {"iata": "FB", "name": "Bulgaria Air", "country": "Bulgaria"},
    "8N": {"iata": "8N", "name": "Barents AirLink", "country": "Sweden"},
    "5C": {"iata": "5C", "name": "CAL Cargo Air Lines", "country": "Israel"},
    "AW": {"iata": "AW", "name": "CHC Airways", "country": "Netherlands"},
    "XG": {"iata": "XG", "name": "Calima Aviacion", "country": "Spain"},
    "R9": {"iata": "R9", "name": "Camai Air", "country": "United States"},
    "UY": {"iata": "UY", "name": "Cameroon Airlines", "country": "Cameroon"},
    "C6": {"iata": "C6", "name": "CanJet", "country": "Canada"},
    "CP": {"iata": "CP", "name": "Canadian Airlines", "country": "Canada"},
    "5T": {"iata": "5T", "name": "Canadian North", "country": "Canada"},
    "W2": {"iata": "W2", "name": "Canadian Western Airlines", "country": "Canada"},
    "9K": {"iata": "9K", "name": "Cape Air", "country": "United States"},
    "PT": {"iata": "PT", "name": "Capital Cargo International Airlines", "country": "United States"},
    "2G": {"iata": "2G", "name": "Cargoitalia", "country": "Italy"},
    "W8": {"iata": "W8", "name": "Cargojet Airways", "country": "Canada"},
    "BW": {"iata": "BW", "name": "Caribbean Airlines", "country": "Trinidad and Tobago"},
    "8B": {"iata": "8B", "name": "Caribbean Star Airlines", "country": "Antigua and Barbuda"},
    "V3": {"iata": "V3", "name": "Carpatair", "country": "Romania"},
    "RV": {"iata": "RV", "name": "Caspian Airlines", "country": "Iran"},
    "CX": {"iata": "CX", "name": "Cathay Pacific", "country": "Hong Kong SAR of China"},
    "KX": {"iata": "KX", "name": "Cayman Airways", "country": "Cayman Islands"},
    "5J": {"iata": "5J", "name": "Cebu Pacific", "country": "Philippines"},
    "7N": {"iata": "7N", "name": "Centavia", "country": "Serbia"},
    "C0": {"iata": "C0", "name": "Centralwings", "country": "Poland"},
    "J7": {"iata": "J7", "name": "Centre-Avia", "country": "Russia"},
    "WE": {"iata": "WE", "name": "Centurion Air Cargo", "country": "United States"},
    "OP": {"iata": "OP", "name": "Chalk's Ocean Airways", "country": "United States"},
    "MG": {"iata": "MG", "name": "Champion Air", "country": "United States"},
    "2Z": {"iata": "2Z", "name": "Changan Airlines", "country": "China"},
    "S8": {"iata": "S8", "name": "Chari Aviation Services", "country": "Chad"},
    "RP": {"iata": "RP", "name": "Chautauqua Airlines", "country": "United States"},
    "C8": {"iata": "C8", "name": "Chicago Express", "country": "United States"},
    "CI": {"iata": "CI", "name": "China Airlines", "country": "Taiwan"},
    "CK": {"iata": "CK", "name": "China Cargo Airlines", "country": "China"},
    "MU": {"iata": "MU", "name": "China Eastern Airlines", "country": "China"},
    "CJ": {"iata": "CJ", "name": "China Northern Airlines", "country": "China"},
    "WH": {"iata": "WH", "name": "China Northwest Airlines", "country": "China"},
    "CZ": {"iata": "CZ", "name": "China Southern Airlines", "country": "China"},
    "HR": {"iata": "HR", "name": "China United Airlines", "country": "China"},
    "XO": {"iata": "XO", "name": "China Xinhua Airlines", "country": "China"},
    "3Q": {"iata": "3Q", "name": "Yunnan Airlines", "country": "China"},
    "X7": {"iata": "X7", "name": "Chitaavia", "country": "Russia"},
    "A2": {"iata": "A2", "name": "Cielos Airlines", "country": "Peru"},
    "QI": {"iata": "QI", "name": "Cimber Air", "country": "Denmark"},
    "C9": {"iata": "C9", "name": "Cirrus Airlines", "country": "Germany"},
    "CF": {"iata": "CF", "name": "City Airline", "country": "Sweden"},
    "G3": {"iata": "G3", "name": "City Connexion Airlines", "country": "Burundi"},
    "WX": {"iata": "WX", "name": "CityJet", "country": "Ireland"},
    "CT": {"iata": "CT", "name": "Civil Air Transport", "country": "Taiwan"},
    "6P": {"iata": "6P", "name": "Club Air", "country": "Italy"},
    "BX": {"iata": "BX", "name": "Coast Air", "country": "Norway"},
    "DQ": {"iata": "DQ", "name": "Coastal Air", "country": "United States"},
    "9L": {"iata": "9L", "name": "Colgan Air", "country": "United States"},
    "OH": {"iata": "OH", "name": "Comair", "country": "United States"},
    "MN": {"iata": "MN", "name": "Comair", "country": "South Africa"},
    "C5": {"iata": "C5", "name": "CommutAir", "country": "United States"},
    "KR": {"iata": "KR", "name": "Comores Airlines", "country": "Comoros"},
    "GJ": {"iata": "GJ", "name": "Compania Mexicargo", "country": "Mexico"},
    "DE": {"iata": "DE", "name": "Condor Flugdienst", "country": "Germany"},
    "6A": {"iata": "6A", "name": "Consorcio Aviaxsa", "country": "Mexico"},
    "C3": {"iata": "C3", "name": "Contact Air", "country": "Germany"},
    "CO": {"iata": "CO", "name": "Continental Airlines", "country": "United States"},
    "CS": {"iata": "CS", "name": "Continental Micronesia", "country": "United States"},
    "V0": {"iata": "V0", "name": "Conviasa", "country": "Venezuela"},
    "CM": {"iata": "CM", "name": "Copa Airlines", "country": "Panama"},
    "SS": {"iata": "SS", "name": "Corsairfly", "country": "France"},
    "XK": {"iata": "XK", "name": "Corse-Mediterranee", "country": "France"},
    "F5": {"iata": "F5", "name": "Cosmic Air", "country": "Nepal"},
    "OU": {"iata": "OU", "name": "Croatia Airlines", "country": "Croatia"},
    "QE": {"iata": "QE", "name": "Crossair Europe", "country": "Switzerland"},
    "CU": {"iata": "CU", "name": "Cubana de Aviación", "country": "Cuba"},
    "CY": {"iata": "CY", "name": "Cyprus Airways", "country": "Cyprus"},
    "YK": {"iata": "YK", "name": "Cyprus Turkish Airlines", "country": "Turkey"},
    "OK": {"iata": "OK", "name": "Czech Airlines", "country": "Czech Republic"},
    "WD": {"iata": "WD", "name": "DAS Air Cargo", "country": "Uganda"},
    "DX": {"iata": "DX", "name": "DAT Danish Air Transport", "country": "Denmark"},
    "ES": {"iata": "ES", "name": "DHL International", "country": "Bahrain"},
    "L3": {"iata": "L3", "name": "DHL de Guatemala", "country": "Guatemala"},
    "D3": {"iata": "D3", "name": "Daallo Airlines", "country": "Djibouti"},
    "N2": {"iata": "N2", "name": "Dagestan Airlines", "country": "Russia"},
    "H8": {"iata": "H8", "name": "Dalavia", "country": "Russia"},
    "0D": {"iata": "0D", "name": "Darwin Airline", "country": "Switzerland"},
    "D5": {"iata": "D5", "name": "Dauair", "country": "Germany"},
    "DL": {"iata": "DL", "name": "Delta Air Lines", "country": "United States"},
    "2A": {"iata": "2A", "name": "Deutsche Bahn", "country": "Germany"},
    "1I": {"iata": "1I", "name": "Deutsche Rettungsflugwacht", "country": "Germany"},
    "D7": {"iata": "D7", "name": "Dinar", "country": "Argentina"},
    "DH": {"iata": "DH", "name": "Discovery Airways", "country": "United States"},
    "D8": {"iata": "D8", "name": "Djibouti Airlines", "country": "Djibouti"},
    "DO": {"iata": "DO", "name": "Dominicana de Aviaci", "country": "Dominican Republic"},
    "E3": {"iata": "E3", "name": "Domodedovo Airlines", "country": "Russia"},
    "KA": {"iata": "KA", "name": "Dragonair", "country": "DRAGON"},
    "KB": {"iata": "KB", "name": "Druk Air", "country": "Bhutan"},
    "DI": {"iata": "DI", "name": "dba", "country": "Germany"},
    "1C": {"iata": "1C", "name": "Electronic Data Systems", "country": "Switzerland"},
    "BR": {"iata": "BR", "name": "EVA Air", "country": "Taiwan"},
    "H7": {"iata": "H7", "name": "Eagle Air", "country": "Uganda"},
    "QU": {"iata": "QU", "name": "East African", "country": "Uganda"},
    "S9": {"iata": "S9", "name": "East African Safari Air", "country": "Kenya"},
    "T3": {"iata": "T3", "name": "Eastern Airways", "country": "United Kingdom"},
    "DK": {"iata": "DK", "name": "Eastland Air", "country": "Australia"},
    "MS": {"iata": "MS", "name": "Egyptair", "country": "Egypt"},
    "LY": {"iata": "LY", "name": "El Al Israel Airlines", "country": "Israel"},
    "UZ": {"iata": "UZ", "name": "El-Buraq Air Transport", "country": "Libya"},
    "EK": {"iata": "EK", "name": "Emirates", "country": "United Arab Emirates"},
    "EU": {"iata": "EU", "name": "Empresa Ecuatoriana De Aviacion", "country": "Ecuador"},
    "E0": {"iata": "E0", "name": "Eos Airlines", "country": "United States"},
    "B8": {"iata": "B8", "name": "Eritrean Airlines", "country": "Eritrea"},
    "E7": {"iata": "E7", "name": "Estafeta Carga Aerea", "country": "Mexico"},
    "OV": {"iata": "OV", "name": "Estonian Air", "country": "Estonia"},
    "ET": {"iata": "ET", "name": "Ethiopian Airlines", "country": "Ethiopia"},
    "EY": {"iata": "EY", "name": "Etihad Airways", "country": "United Arab Emirates"},
    "RZ": {"iata": "RZ", "name": "Euro Exec Express", "country": "Sweden"},
    "MM": {"iata": "MM", "name": "EuroAtlantic Airways", "country": "Portugal"},
    "UI": {"iata": "UI", "name": "Eurocypria Airlines", "country": "Cyprus"},
    "K2": {"iata": "K2", "name": "Eurolot", "country": "Poland"},
    "3W": {"iata": "3W", "name": "Euromanx Airways", "country": "Austria"},
    "5O": {"iata": "5O", "name": "ASL Airlines France", "country": "France"},
    "EA": {"iata": "EA", "name": "European Air Express", "country": "Germany"},
    "QY": {"iata": "QY", "name": "European Air Transport", "country": "Belgium"},
    "EW": {"iata": "EW", "name": "Eurowings", "country": "Germany"},
    "EZ": {"iata": "EZ", "name": "Evergreen International Airlines", "country": "United States"},
    "JN": {"iata": "JN", "name": "Excel Airways", "country": "United Kingdom"},
    "MB": {"iata": "MB", "name": "Execair Aviation", "country": "Canada"},
    "OW": {"iata": "OW", "name": "Executive Airlines", "country": "United States"},
    "EO": {"iata": "EO", "name": "Express One International", "country": "United States"},
    "XE": {"iata": "XE", "name": "ExpressJet", "country": "United States"},
    "U2": {"iata": "U2", "name": "easyJet", "country": "United Kingdom"},
    "IH": {"iata": "IH", "name": "Falcon Aviation", "country": "Sweden"},
    "EF": {"iata": "EF", "name": "Far Eastern Air Transport", "country": "Taiwan"},
    "F6": {"iata": "F6", "name": "Faroejet", "country": "Faroe Islands"},
    "F3": {"iata": "F3", "name": "Faso Airways", "country": "Burkina Faso"},
    "FX": {"iata": "FX", "name": "Federal Express", "country": "United States"},
    "N8": {"iata": "N8", "name": "Fika Salaama Airlines", "country": "Uganda"},
    "4S": {"iata": "4S", "name": "Finalair Congo", "country": "Republic of the Congo"},
    "AY": {"iata": "AY", "name": "Finnair", "country": "Finland"},
    "FC": {"iata": "FC", "name": "Finncomm Airlines", "country": "Finland"},
    "FY": {"iata": "FY", "name": "Firefly", "country": "Malaysia"},
    "7F": {"iata": "7F", "name": "First Air", "country": "Canada"},
    "DP": {"iata": "DP", "name": "First Choice Airways", "country": "United Kingdom"},
    "8F": {"iata": "8F", "name": "Fischer Air", "country": "Czech Republic"},
    "B5": {"iata": "B5", "name": "Flightline", "country": "United Kingdom"},
    "PA": {"iata": "PA", "name": "Florida Coastal Airlines", "country": "United States"},
    "RF": {"iata": "RF", "name": "Florida West International Airways", "country": "United States"},
    "F2": {"iata": "F2", "name": "Fly Air", "country": "Turkey"},
    "SH": {"iata": "SH", "name": "Fly Me Sweden", "country": "Sweden"},
    "TE": {"iata": "TE", "name": "FlyLal", "country": "Lithuania"},
    "LF": {"iata": "LF", "name": "FlyNordic", "country": "Sweden"},
    "F7": {"iata": "F7", "name": "Flybaboo", "country": "Switzerland"},
    "BE": {"iata": "BE", "name": "Flybe", "country": "United Kingdom"},
    "VY": {"iata": "VY", "name": "Formosa Airlines", "country": "Taiwan"},
    "HK": {"iata": "HK", "name": "Four Star Aviation / Four Star Cargo", "country": "United States"},
    "FP": {"iata": "FP", "name": "Freedom Air", "country": "United States"},
    "F9": {"iata": "F9", "name": "Frontier Airlines", "country": "United States"},
    "2F": {"iata": "2F", "name": "Frontier Flying Service", "country": "United States"},
    "FH": {"iata": "FH", "name": "Futura International Airways", "country": "Spain"},
    "GT": {"iata": "GT", "name": "GB Airways", "country": "United Kingdom"},
    "7O": {"iata": "7O", "name": "Galaxy Air", "country": "Kyrgyzstan"},
    "1G": {"iata": "1G", "name": "Galileo International", "country": "United States"},
    "GC": {"iata": "GC", "name": "Gambia International Airlines", "country": "Gambia"},
    "G7": {"iata": "G7", "name": "Gandalf Airlines", "country": "Italy"},
    "GA": {"iata": "GA", "name": "Garuda Indonesia", "country": "Indonesia"},
    "A9": {"iata": "A9", "name": "Georgian Airways", "country": "Georgia"},
    "QB": {"iata": "QB", "name": "Georgian National Airlines", "country": "Georgia"},
    "ST": {"iata": "ST", "name": "Germania", "country": "Germany"},
    "4U": {"iata": "4U", "name": "Germanwings", "country": "Germany"},
    "GP": {"iata": "GP", "name": "Gestair", "country": "Spain"},
    "G0": {"iata": "G0", "name": "Ghana International Airlines", "country": "Ghana"},
    "GK": {"iata": "GK", "name": "Go One Airways", "country": "United Kingdom"},
    "DC": {"iata": "DC", "name": "Golden Air", "country": "Sweden"},
    "G1": {"iata": "G1", "name": "Gorkha Airlines", "country": "Nepal"},
    "ZK": {"iata": "ZK", "name": "Great Lakes Airlines", "country": "United States"},
    "IJ": {"iata": "IJ", "name": "Great Wall Airlines", "country": "China"},
    "TA": {"iata": "TA", "name": "Grupo TACA", "country": "Costa Rica"},
    "G6": {"iata": "G6", "name": "Guine Bissaur Airlines", "country": "Guinea-Bissau"},
    "J9": {"iata": "J9", "name": "Guinee Airlines", "country": "Guinea"},
    "GF": {"iata": "GF", "name": "Gulf Air Bahrain", "country": "Bahrain"},
    "GY": {"iata": "GY", "name": "Guyana Airways 2000", "country": ""},
    "H6": {"iata": "H6", "name": "Hageland Aviation Services", "country": "United States"},
    "HU": {"iata": "HU", "name": "Hainan Airlines", "country": "China"},
    "1R": {"iata": "1R", "name": "Hainan Phoenix Information Systems", "country": "China"},
    "2T": {"iata": "2T", "name": "Haiti Ambassador Airlines", "country": "Haiti"},
    "4R": {"iata": "4R", "name": "Hamburg International", "country": "Germany"},
    "X3": {"iata": "X3", "name": "TUIfly", "country": "Germany"},
    "HF": {"iata": "HF", "name": "Hapagfly", "country": "Germany"},
    "HB": {"iata": "HB", "name": "Harbor Airlines", "country": "United States"},
    "HQ": {"iata": "HQ", "name": "Harmony Airways", "country": "Canada"},
    "HA": {"iata": "HA", "name": "Hawaiian Airlines", "country": "United States"},
    "BH": {"iata": "BH", "name": "Hawkair", "country": "Canada"},
    "HN": {"iata": "HN", "name": "Heavylift Cargo Airlines", "country": "Australia"},
    "8H": {"iata": "8H", "name": "Heli France", "country": "France"},
    "JB": {"iata": "JB", "name": "Helijet", "country": "Canada"},
    "ZU": {"iata": "ZU", "name": "Helios Airways", "country": "Cyprus"},
    "T4": {"iata": "T4", "name": "Hellas Jet", "country": "Greece"},
    "HW": {"iata": "HW", "name": "Hello", "country": "Switzerland"},
    "2L": {"iata": "2L", "name": "Helvetic Airways", "country": "Switzerland"},
    "DU": {"iata": "DU", "name": "Hemus Air", "country": "Bulgaria"},
    "UD": {"iata": "UD", "name": "Hex'Air", "country": "France"},
    "5K": {"iata": "5K", "name": "Hi Fly", "country": "Portugal"},
    "HD": {"iata": "HD", "name": "Hokkaido International Airlines", "country": "Japan"},
    "H5": {"iata": "H5", "name": "Hola Airlines", "country": "Spain"},
    "HX": {"iata": "HX", "name": "Hong Kong Airlines", "country": "Hong Kong SAR of China"},
    "UO": {"iata": "UO", "name": "Hong Kong Express Airways", "country": "Hong Kong SAR of China"},
    "HH": {"iata": "HH", "name": "Hope Air", "country": "Canada"},
    "QX": {"iata": "QX", "name": "Horizon Air", "country": "United States"},
    "H4": {"iata": "H4", "name": "Héli Sécurité Helicopter Airlines", "country": "France"},
    "II": {"iata": "II", "name": "IBC Airways", "country": "United States"},
    "1F": {"iata": "1F", "name": "INFINI Travel Information", "country": "Japan"},
    "1U": {"iata": "1U", "name": "ITA Software", "country": "United States"},
    "IB": {"iata": "IB", "name": "Iberia Airlines", "country": "Spain"},
    "FW": {"iata": "FW", "name": "Ibex Airlines", "country": "Japan"},
    "FI": {"iata": "FI", "name": "Icelandair", "country": "Iceland"},
    "IK": {"iata": "IK", "name": "Imair Airlines", "country": "Azerbaijan"},
    "6E": {"iata": "6E", "name": "IndiGo Airlines", "country": "India"},
    "IC": {"iata": "IC", "name": "Indian Airlines", "country": "India"},
    "QZ": {"iata": "QZ", "name": "Indonesia AirAsia", "country": "Indonesia"},
    "IO": {"iata": "IO", "name": "Indonesian Airlines", "country": "Indonesia"},
    "D6": {"iata": "D6", "name": "Interair South Africa", "country": "South Africa"},
    "RS": {"iata": "RS", "name": "Intercontinental de Aviaci", "country": "Colombia"},
    "ID": {"iata": "ID", "name": "Interlink Airlines", "country": "South Africa"},
    "6I": {"iata": "6I", "name": "International Business Air", "country": "Sweden"},
    "3L": {"iata": "3L", "name": "Intersky", "country": "Austria"},
    "I4": {"iata": "I4", "name": "Interstate Airline", "country": "Netherlands"},
    "IR": {"iata": "IR", "name": "Iran Air", "country": "Iran"},
    "EP": {"iata": "EP", "name": "Iran Aseman Airlines", "country": "Iran"},
    "IA": {"iata": "IA", "name": "Iraqi Airways", "country": "Iraq"},
    "IS": {"iata": "IS", "name": "Island Airlines", "country": "United States"},
    "2S": {"iata": "2S", "name": "Island Express", "country": "United States"},
    "8L": {"iata": "8L", "name": "Cargo Plus Aviation", "country": "United Arab Emirates"},
    "CN": {"iata": "CN", "name": "Islands Nationair", "country": "Papua New Guinea"},
    "IF": {"iata": "IF", "name": "Islas Airways", "country": "Spain"},
    "WC": {"iata": "WC", "name": "Islena De Inversiones", "country": "Honduras"},
    "6H": {"iata": "6H", "name": "Israir", "country": "Israel"},
    "9X": {"iata": "9X", "name": "Itali Airlines", "country": "Italy"},
    "GI": {"iata": "GI", "name": "Itek Air", "country": "Kyrgyzstan"},
    "JC": {"iata": "JC", "name": "JAL Express", "country": "Japan"},
    "JO": {"iata": "JO", "name": "JALways", "country": "Japan"},
    "1M": {"iata": "1M", "name": "JSC Transport Automated Information Systems", "country": "Russia"},
    "JL": {"iata": "JL", "name": "Japan Airlines", "country": "Japan"},
    "EG": {"iata": "EG", "name": "Japan Asia Airways", "country": "Japan"},
    "NU": {"iata": "NU", "name": "Japan Transocean Air", "country": "Japan"},
    "JU": {"iata": "JU", "name": "Jat Airways", "country": "Serbia"},
    "VJ": {"iata": "VJ", "name": "Jatayu Airlines", "country": "Indonesia"},
    "7C": {"iata": "7C", "name": "Jeju Air", "country": "Republic of Korea"},
    "9W": {"iata": "9W", "name": "Jet Airways", "country": "India"},
    "QJ": {"iata": "QJ", "name": "Jet Airways", "country": "United States"},
    "0J": {"iata": "0J", "name": "Jetclub", "country": "Switzerland"},
    "3K": {"iata": "3K", "name": "Jetstar Asia Airways", "country": "Singapore"},
    "LS": {"iata": "LS", "name": "Jet2.com", "country": "United Kingdom"},
    "8J": {"iata": "8J", "name": "Jet4You", "country": "Morocco"},
    "B6": {"iata": "B6", "name": "JetBlue Airways", "country": "United States"},
    "JF": {"iata": "JF", "name": "Jetairfly", "country": "Belgium"},
    "SG": {"iata": "SG", "name": "JetsGo", "country": "Canada"},
    "JQ": {"iata": "JQ", "name": "Jetstar Airways", "country": "Australia"},
    "JX": {"iata": "JX", "name": "Jett8 Airlines Cargo", "country": "Singapore"},
    "GX": {"iata": "GX", "name": "Jetx Airlines", "country": "Iceland"},
    "R5": {"iata": "R5", "name": "Jordan Aviation", "country": "Jordan"},
    "KD": {"iata": "KD", "name": "KD Avia", "country": "Russia"},
    "WA": {"iata": "WA", "name": "KLM Cityhopper", "country": "Netherlands"},
    "KL": {"iata": "KL", "name": "KLM Royal Dutch Airlines", "country": "Netherlands"},
    "K4": {"iata": "K4", "name": "Kalitta Air", "country": "United States"},
    "RQ": {"iata": "RQ", "name": "Kam Air", "country": "Afghanistan"},
    "E2": {"iata": "E2", "name": "Kampuchea Airlines", "country": "Cambodia"},
    "V2": {"iata": "V2", "name": "Karat", "country": "Russia"},
    "KV": {"iata": "KV", "name": "Kavminvodyavia", "country": "Russia"},
    "M5": {"iata": "M5", "name": "Kenmore Air", "country": "United States"},
    "KQ": {"iata": "KQ", "name": "Kenya Airways", "country": "Kenya"},
    "IT": {"iata": "IT", "name": "Kingfisher Airlines", "country": "India"},
    "Y9": {"iata": "Y9", "name": "Kish Air", "country": "Iran"},
    "KP": {"iata": "KP", "name": "Kiwi International Air Lines", "country": "United States"},
    "7K": {"iata": "7K", "name": "Kogalymavia Air Company", "country": "Russia"},
    "KE": {"iata": "KE", "name": "Korean Air", "country": "Republic of Korea"},
    "7B": {"iata": "7B", "name": "Krasnojarsky Airlines", "country": "Russia"},
    "K9": {"iata": "K9", "name": "Krylo Airlines", "country": "Russia"},
    "GW": {"iata": "GW", "name": "Kuban Airlines", "country": "Russia"},
    "KU": {"iata": "KU", "name": "Kuwait Airways", "country": "Kuwait"},
    "GO": {"iata": "GO", "name": "Kuzu Airlines Cargo", "country": "Turkey"},
    "N5": {"iata": "N5", "name": "Kyrgyz Airlines", "country": "Kyrgyzstan"},
    "R8": {"iata": "R8", "name": "Kyrgyzstan Airlines", "country": "Kyrgyzstan"},
    "LR": {"iata": "LR", "name": "LACSA", "country": "Costa Rica"},
    "KG": {"iata": "KG", "name": "LAI - Linea Aerea IAACA", "country": "Venezuela"},
    "LA": {"iata": "LA", "name": "LAN Airlines", "country": "Chile"},
    "4M": {"iata": "4M", "name": "LAN Argentina", "country": "Argentina"},
    "LU": {"iata": "LU", "name": "LAN Express", "country": "Chile"},
    "LP": {"iata": "LP", "name": "LAN Peru", "country": "Peru"},
    "LO": {"iata": "LO", "name": "LOT Polish Airlines", "country": "Poland"},
    "LT": {"iata": "LT", "name": "LTU International", "country": "Germany"},
    "N6": {"iata": "N6", "name": "Lagun Air", "country": "Spain"},
    "QV": {"iata": "QV", "name": "Lao Airlines", "country": "Lao Peoples Democratic Republic"},
    "L7": {"iata": "L7", "name": "Laoag International Airlines", "country": "Philippines"},
    "NG": {"iata": "NG", "name": "Lauda Air", "country": "Austria"},
    "LQ": {"iata": "LQ", "name": "Lebanese Air Transport", "country": "Lebanon"},
    "LI": {"iata": "LI", "name": "Leeward Islands Air Transport", "country": "Antigua and Barbuda"},
    "LN": {"iata": "LN", "name": "Libyan Arab Airlines", "country": "Libya"},
    "8z": {"iata": "8z", "name": "Linea Aerea de Servicio Ejecutivo Regional", "country": "Venezuela"},
    "LM": {"iata": "LM", "name": "Linhas A", "country": "Mozambique"},
    "JT": {"iata": "JT", "name": "Lion Mentari Airlines", "country": "Indonesia"},
    "LB": {"iata": "LB", "name": "Lloyd Aereo Boliviano", "country": "Bolivia"},
    "HE": {"iata": "HE", "name": "Luftfahrtgesellschaft Walter", "country": "Germany"},
    "LH": {"iata": "LH", "name": "Lufthansa", "country": "Germany"},
    "CL": {"iata": "CL", "name": "Lufthansa CityLine", "country": "Germany"},
    "L1": {"iata": "L1", "name": "Lufthansa Systems", "country": "Germany"},
    "DV": {"iata": "DV", "name": "Lufttaxi Fluggesellschaft", "country": "Germany"},
    "L5": {"iata": "L5", "name": "Lufttransport", "country": "Norway"},
    "LG": {"iata": "LG", "name": "Luxair", "country": "Luxembourg"},
    "5V": {"iata": "5V", "name": "Lviv Airlines", "country": "Ukraine"},
    "L2": {"iata": "L2", "name": "Lynden Air Cargo", "country": "United States"},
    "MJ": {"iata": "MJ", "name": "L", "country": "Argentina"},
    "M7": {"iata": "M7", "name": "MasAir", "country": "Mexico"},
    "IN": {"iata": "IN", "name": "MAT Macedonian Airlines", "country": "Macedonia"},
    "OM": {"iata": "OM", "name": "MIAT Mongolian Airlines", "country": "Mongolia"},
    "DM": {"iata": "DM", "name": "Maersk", "country": "Denmark"},
    "W5": {"iata": "W5", "name": "Mahan Air", "country": "Iran"},
    "M2": {"iata": "M2", "name": "Mahfooz Aviation", "country": "Gambia"},
    "MH": {"iata": "MH", "name": "Malaysia Airlines", "country": "Malaysia"},
    "TF": {"iata": "TF", "name": "Malmö Aviation", "country": "Sweden"},
    "MA": {"iata": "MA", "name": "Malév", "country": "Hungary"},
    "RI": {"iata": "RI", "name": "Mandala Airlines", "country": "Indonesia"},
    "AE": {"iata": "AE", "name": "Mandarin Airlines", "country": "Taiwan"},
    "JE": {"iata": "JE", "name": "Mango", "country": "South Africa"},
    "MP": {"iata": "MP", "name": "Martinair", "country": "Netherlands"},
    "Q4": {"iata": "Q4", "name": "Mastertop Linhas Aereas", "country": "Brazil"},
    "8M": {"iata": "8M", "name": "Maxair", "country": "Sweden"},
    "MY": {"iata": "MY", "name": "Maxjet Airways", "country": "United States"},
    "MW": {"iata": "MW", "name": "Maya Island Air", "country": "Belize"},
    "0F": {"iata": "0F", "name": "Mediterranean Air Freight", "country": "Greece"},
    "IM": {"iata": "IM", "name": "Menajet", "country": "Lebanon"},
    "IG": {"iata": "IG", "name": "Meridiana", "country": "Italy"},
    "MZ": {"iata": "MZ", "name": "Merpati Nusantara Airlines", "country": "Indonesia"},
    "YV": {"iata": "YV", "name": "Mesa Airlines", "country": "United States"},
    "XJ": {"iata": "XJ", "name": "Mesaba Airlines", "country": "United States"},
    "MX": {"iata": "MX", "name": "Mexicana de Aviaci", "country": "Mexico"},
    "ME": {"iata": "ME", "name": "Middle East Airlines", "country": "Lebanon"},
    "JI": {"iata": "JI", "name": "Midway Airlines", "country": "United States"},
    "YX": {"iata": "YX", "name": "Midwest Airlines", "country": "United States"},
    "2M": {"iata": "2M", "name": "Moldavian Airlines", "country": "Moldova"},
    "8I": {"iata": "8I", "name": "Myway Airlines", "country": "Italy"},
    "YM": {"iata": "YM", "name": "Montenegro Airlines", "country": "Montenegro"},
    "3R": {"iata": "3R", "name": "Moskovia Airlines", "country": "Russia"},
    "M9": {"iata": "M9", "name": "Motor Sich", "country": "Ukraine"},
    "N4": {"iata": "N4", "name": "Mountain Air Company", "country": "Sierra Leone"},
    "VZ": {"iata": "VZ", "name": "MyTravel Airways", "country": "United Kingdom"},
    "UB": {"iata": "UB", "name": "Myanma Airways", "country": "Myanmar"},
    "P9": {"iata": "P9", "name": "Nas Air", "country": "Mali"},
    "UE": {"iata": "UE", "name": "Nasair", "country": "Eritrea"},
    "N7": {"iata": "N7", "name": "National Airlines", "country": "United States"},
    "NA": {"iata": "NA", "name": "National Airlines", "country": "United States"},
    "9O": {"iata": "9O", "name": "National Airways Cameroon", "country": "Cameroon"},
    "NC": {"iata": "NC", "name": "National Jet Systems", "country": "Australia"},
    "CE": {"iata": "CE", "name": "Nationwide Airlines", "country": "South Africa"},
    "ON": {"iata": "ON", "name": "Nauru Air Corporation", "country": "Nauru"},
    "1N": {"iata": "1N", "name": "Navitaire", "country": "United States"},
    "RA": {"iata": "RA", "name": "Nepal Airlines", "country": "Nepal"},
    "EJ": {"iata": "EJ", "name": "New England Airlines", "country": "United States"},
    "2N": {"iata": "2N", "name": "NextJet", "country": "Sweden"},
    "HG": {"iata": "HG", "name": "Niki", "country": "Austria"},
    "KZ": {"iata": "KZ", "name": "Nippon Cargo Airlines", "country": "Japan"},
    "DD": {"iata": "DD", "name": "Nok Air", "country": "Thailand"},
    "JH": {"iata": "JH", "name": "Nordeste Linhas Aereas Regionais", "country": "Brazil"},
    "6N": {"iata": "6N", "name": "Nordic Regional", "country": "Sweden"},
    "N9": {"iata": "N9", "name": "North Coast Aviation", "country": "Papua New Guinea"},
    "U7": {"iata": "U7", "name": "Northern Dene Airways", "country": "Canada"},
    "NW": {"iata": "NW", "name": "Northwest Airlines", "country": "United States"},
    "J3": {"iata": "J3", "name": "Northwestern Air", "country": "Canada"},
    "DY": {"iata": "DY", "name": "Norwegian Air Shuttle", "country": "Norway"},
    "BJ": {"iata": "BJ", "name": "Nouvel Air Tunisie", "country": "Tunisia"},
    "M4": {"iata": "M4", "name": "Nova Airline", "country": "Sudan"},
    "XY": {"iata": "XY", "name": "Nas Air", "country": "Saudi Arabia"},
    "UQ": {"iata": "UQ", "name": "O'Connor Airlines", "country": "Australia"},
    "CR": {"iata": "CR", "name": "OAG", "country": "United Kingdom"},
    "O8": {"iata": "O8", "name": "Oasis Hong Kong Airlines", "country": "Hong Kong"},
    "VC": {"iata": "VC", "name": "Ocean Airlines", "country": "Italy"},
    "O6": {"iata": "O6", "name": "Oceanair", "country": "Brazil"},
    "O2": {"iata": "O2", "name": "Oceanic Airlines", "country": "Guinea"},
    "OA": {"iata": "OA", "name": "Olympic Airlines", "country": "Greece"},
    "WY": {"iata": "WY", "name": "Oman Air", "country": "Oman"},
    "OY": {"iata": "OY", "name": "Omni Air International", "country": "United States"},
    "N3": {"iata": "N3", "name": "Omskavia Airline", "country": "Russia"},
    "R2": {"iata": "R2", "name": "Orenburg Airlines", "country": "Russia"},
    "OX": {"iata": "OX", "name": "Orient Thai Airlines", "country": "Thailand"},
    "OL": {"iata": "OL", "name": "Ostfriesische Lufttransport", "country": "Germany"},
    "OJ": {"iata": "OJ", "name": "Overland Airways", "country": "Nigeria"},
    "O7": {"iata": "O7", "name": "Ozjet Airlines", "country": "Australia"},
    "PV": {"iata": "PV", "name": "PAN Air", "country": "Spain"},
    "9Q": {"iata": "9Q", "name": "PB Air", "country": "Thailand"},
    "PU": {"iata": "PU", "name": "PLUNA", "country": "Uruguay"},
    "U4": {"iata": "U4", "name": "PMTair", "country": "Cambodia"},
    "Y5": {"iata": "Y5", "name": "Pace Airlines", "country": "United States"},
    "BL": {"iata": "BL", "name": "Jetstar Pacific", "country": "Vietnam"},
    "DJ": {"iata": "DJ", "name": "Pacific Blue", "country": "New Zealand"},
    "8P": {"iata": "8P", "name": "Pacific Coastal Airline", "country": "Canada"},
    "Q8": {"iata": "Q8", "name": "Pacific East Asia Cargo Airlines", "country": "Philippines"},
    "PS": {"iata": "PS", "name": "Pacific Southwest Airlines", "country": "United States"},
    "LW": {"iata": "LW", "name": "Pacific Wings", "country": "United States"},
    "PK": {"iata": "PK", "name": "Pakistan International Airlines", "country": "Pakistan"},
    "PF": {"iata": "PF", "name": "Palestinian Airlines", "country": "Egypt"},
    "NR": {"iata": "NR", "name": "Pamir Airways", "country": "Afghanistan"},
    "PQ": {"iata": "PQ", "name": "Panafrican Airways", "country": "Ivory Coast"},
    "P8": {"iata": "P8", "name": "Pantanal Linhas Aéreas", "country": "Brazil"},
    "I7": {"iata": "I7", "name": "Paramount Airways", "country": "India"},
    "KS": {"iata": "KS", "name": "Peninsula Airways", "country": "United States"},
    "PR": {"iata": "PR", "name": "Philippine Airlines", "country": "Philippines"},
    "9R": {"iata": "9R", "name": "Phuket Air", "country": "Thailand"},
    "PI": {"iata": "PI", "name": "Piedmont Airlines (1948-1989)", "country": "United States"},
    "9E": {"iata": "9E", "name": "Pinnacle Airlines", "country": "United States"},
    "PO": {"iata": "PO", "name": "Polar Air Cargo", "country": "United States"},
    "PH": {"iata": "PH", "name": "Polynesian Airlines", "country": "Samoa"},
    "PD": {"iata": "PD", "name": "Porter Airlines", "country": "Canada"},
    "NI": {"iata": "NI", "name": "Portugalia", "country": "Portugal"},
    "BK": {"iata": "BK", "name": "Potomac Air", "country": "United States"},
    "PW": {"iata": "PW", "name": "Precision Air", "country": "Tanzania"},
    "TO": {"iata": "TO", "name": "President Airlines", "country": "Cambodia"},
    "FE": {"iata": "FE", "name": "Primaris Airlines", "country": "United States"},
    "P0": {"iata": "P0", "name": "Proflight Commuter Services", "country": "Zambia"},
    "QF": {"iata": "QF", "name": "Qantas", "country": "Australia"},
    "QR": {"iata": "QR", "name": "Qatar Airways", "country": "Qatar"},
    "R6": {"iata": "R6", "name": "RACSA", "country": "Guatemala"},
    "1D": {"iata": "1D", "name": "Radixx Solutions International", "country": "United States"},
    "V4": {"iata": "V4", "name": "Reem Air", "country": "Kyrgyzstan"},
    "FN": {"iata": "FN", "name": "Regional Airlines", "country": "Morocco"},
    "ZL": {"iata": "ZL", "name": "Regional Express", "country": "Australia"},
    "3C": {"iata": "3C", "name": "RegionsAir", "country": "United States"},
    "RW": {"iata": "RW", "name": "Republic Airlines", "country": "United States"},
    "RH": {"iata": "RH", "name": "Republic Express Airlines", "country": "Indonesia"},
    "C7": {"iata": "C7", "name": "Rico Linhas A", "country": "Brazil"},
    "SL": {"iata": "SL", "name": "Rio Sul Servi", "country": "Brazil"},
    "R4": {"iata": "R4", "name": "Rossiya", "country": "Russia"},
    "GZ": {"iata": "GZ", "name": "Air Rarotonga", "country": "Cook Islands"},
    "RR": {"iata": "RR", "name": "Royal Air Force", "country": "United Kingdom"},
    "AT": {"iata": "AT", "name": "Royal Air Maroc", "country": "Morocco"},
    "R0": {"iata": "R0", "name": "Royal Airlines", "country": "Pakistan"},
    "BI": {"iata": "BI", "name": "Royal Brunei Airlines", "country": "Brunei"},
    "RJ": {"iata": "RJ", "name": "Royal Jordanian", "country": "Jordan"},
    "WR": {"iata": "WR", "name": "Royal Tongan Airlines", "country": "Tonga"},
    "P7": {"iata": "P7", "name": "Russian Sky Airlines", "country": "Russia"},
    "WB": {"iata": "WB", "name": "Rwandair Express", "country": "Rwanda"},
    "RD": {"iata": "RD", "name": "Ryan International Airlines", "country": "United States"},
    "FR": {"iata": "FR", "name": "Ryanair", "country": "Ireland"},
    "YS": {"iata": "YS", "name": "Régional", "country": "France"},
    "S4": {"iata": "S4", "name": "SATA International", "country": "Portugal"},
    "SA": {"iata": "SA", "name": "South African Airways", "country": "South Africa"},
    "NL": {"iata": "NL", "name": "Shaheen Air International", "country": "Pakistan"},
    "SK": {"iata": "SK", "name": "Scandinavian Airlines System", "country": "Sweden"},
    "S7": {"iata": "S7", "name": "S7 Airlines", "country": "Russia"},
    "BB": {"iata": "BB", "name": "Seaborne Airlines", "country": "United States"},
    "UL": {"iata": "UL", "name": "SriLankan Airlines", "country": "Sri Lanka"},
    "SY": {"iata": "SY", "name": "Sun Country Airlines", "country": "United States"},
    "I6": {"iata": "I6", "name": "Sky Eyes", "country": "Thailand"},
    "7G": {"iata": "7G", "name": "Star Flyer", "country": "Japan"},
    "FA": {"iata": "FA", "name": "Safair", "country": "South Africa"},
    "SP": {"iata": "SP", "name": "SATA Air Acores", "country": "Portugal"},
    "8S": {"iata": "8S", "name": "Scorpio Aviation", "country": ""},
    "SQ": {"iata": "SQ", "name": "Singapore Airlines", "country": "Singapore"},
    "5M": {"iata": "5M", "name": "Sibaviatrans", "country": "Russia"},
    "SI": {"iata": "SI", "name": "Skynet Airlines", "country": "Ireland"},
    "XS": {"iata": "XS", "name": "SITA", "country": "Belgium"},
    "SJ": {"iata": "SJ", "name": "Sriwijaya Air", "country": "Indonesia"},
    "ZS": {"iata": "ZS", "name": "Sama Airlines", "country": "Saudi Arabia"},
    "FT": {"iata": "FT", "name": "Siem Reap Airways", "country": "Cambodia"},
    "SX": {"iata": "SX", "name": "Sky Work Airlines", "country": "Switzerland"},
    "SM": {"iata": "SM", "name": "Swedline Express", "country": "Sweden"},
    "DG": {"iata": "DG", "name": "South East Asian Airlines", "country": "Philippines"},
    "5G": {"iata": "5G", "name": "Skyservice Airlines", "country": "Canada"},
    "FS": {"iata": "FS", "name": "Servicios de Transportes A", "country": "Argentina"},
    "SD": {"iata": "SD", "name": "Sudan Airways", "country": "Sudan"},
    "SV": {"iata": "SV", "name": "Saudi Arabian Airlines", "country": "Saudi Arabia"},
    "WN": {"iata": "WN", "name": "Southwest Airlines", "country": "United States"},
    "A4": {"iata": "A4", "name": "Southern Winds Airlines", "country": "Argentina"},
    "WG": {"iata": "WG", "name": "Sunwing Airlines", "country": "Canada"},
    "LX": {"iata": "LX", "name": "Swiss International Air Lines", "country": "Switzerland"},
    "SR": {"iata": "SR", "name": "Swissair", "country": "Switzerland"},
    "WV": {"iata": "WV", "name": "Swe Fly", "country": "Sweden"},
    "XQ": {"iata": "XQ", "name": "SunExpress", "country": "Turkey"},
    "AL": {"iata": "AL", "name": "Skywalk Airlines", "country": "United States"},
    "ZP": {"iata": "ZP", "name": "Silk Way Airlines", "country": "Azerbaijan"},
    "E5": {"iata": "E5", "name": "Samara Airlines", "country": "Russia"},
    "SC": {"iata": "SC", "name": "Shandong Airlines", "country": "China"},
    "9S": {"iata": "9S", "name": "Spring Airlines", "country": "China"},
    "3U": {"iata": "3U", "name": "Sichuan Airlines", "country": "China"},
    "FM": {"iata": "FM", "name": "Shanghai Airlines", "country": "China"},
    "ZH": {"iata": "ZH", "name": "Shenzhen Airlines", "country": "China"},
    "7L": {"iata": "7L", "name": "Sun D'Or", "country": "Israel"},
    "NE": {"iata": "NE", "name": "SkyEurope", "country": "Slovakia"},
    "CQ": {"iata": "CQ", "name": "Sunshine Express Airlines", "country": "Australia"},
    "SO": {"iata": "SO", "name": "Superior Aviation", "country": "United States"},
    "JK": {"iata": "JK", "name": "Spanair", "country": "Spain"},
    "1Z": {"iata": "1Z", "name": "Sabre Pacific", "country": "Australia"},
    "1S": {"iata": "1S", "name": "Sabre", "country": "United States"},
    "1H": {"iata": "1H", "name": "Siren-Travel", "country": "Russia"},
    "1Q": {"iata": "1Q", "name": "Sirena", "country": "Russia"},
    "1K": {"iata": "1K", "name": "Southern Cross Distribution", "country": "Australia"},
    "2C": {"iata": "2C", "name": "SNCF", "country": "France"},
    "NK": {"iata": "NK", "name": "Spirit Airlines", "country": "United States"},
    "S0": {"iata": "S0", "name": "Slok Air Gambia", "country": "Gambia"},
    "S3": {"iata": "S3", "name": "Santa Barbara Airlines", "country": "Venezuela"},
    "H2": {"iata": "H2", "name": "Sky Airline", "country": "Chile"},
    "OO": {"iata": "OO", "name": "SkyWest", "country": "United States"},
    "JZ": {"iata": "JZ", "name": "Skyways Express", "country": "Sweden"},
    "BC": {"iata": "BC", "name": "Skymark Airlines", "country": "Japan"},
    "LJ": {"iata": "LJ", "name": "Sierra National Airlines", "country": "Sierra Leone"},
    "0E": {"iata": "0E", "name": "Silver Air", "country": "Czech Republic"},
    "MI": {"iata": "MI", "name": "SilkAir", "country": "Singapore"},
    "6Q": {"iata": "6Q", "name": "Slovak Airlines", "country": "Slovakia"},
    "PY": {"iata": "PY", "name": "Surinam Airways", "country": "Suriname"},
    "NB": {"iata": "NB", "name": "Sterling Airlines", "country": "Denmark"},
    "6J": {"iata": "6J", "name": "Skynet Asia Airways", "country": "Japan"},
    "IE": {"iata": "IE", "name": "Solomon Airlines", "country": "Solomon Islands"},
    "6W": {"iata": "6W", "name": "Saratov Aviation Division", "country": "Russia"},
    "HZ": {"iata": "HZ", "name": "Sat Airlines", "country": "Kazakhstan"},
    "S5": {"iata": "S5", "name": "Shuttle America", "country": "United States"},
    "R1": {"iata": "R1", "name": "Sirin", "country": ""},
    "S6": {"iata": "S6", "name": "Star Air", "country": "Denmark"},
    "EQ": {"iata": "EQ", "name": "TAME", "country": "Ecuador"},
    "JJ": {"iata": "JJ", "name": "TAM Brazilian Airlines", "country": "Brazil"},
    "TP": {"iata": "TP", "name": "TAP Portugal", "country": "Portugal"},
    "TU": {"iata": "TU", "name": "Tunisair", "country": "Tunisia"},
    "3V": {"iata": "3V", "name": "ASL Airlines Belgium", "country": "Belgium"},
    "T2": {"iata": "T2", "name": "Thai Air Cargo", "country": "Thailand"},
    "FQ": {"iata": "FQ", "name": "Thomas Cook Airlines", "country": "Belgium"},
    "MT": {"iata": "MT", "name": "Thomas Cook Airlines", "country": "United Kingdom"},
    "TQ": {"iata": "TQ", "name": "Tandem Aero", "country": "Moldova"},
    "L9": {"iata": "L9", "name": "Teamline Air", "country": "Austria"},
    "ZT": {"iata": "ZT", "name": "Titan Airways", "country": "United Kingdom"},
    "TR": {"iata": "TR", "name": "Tiger Airways", "country": "Singapore"},
    "TG": {"iata": "TG", "name": "Thai Airways International", "country": "Thailand"},
    "FD": {"iata": "FD", "name": "Thai AirAsia", "country": "Thailand"},
    "TK": {"iata": "TK", "name": "Turkish Airlines", "country": "Turkey"},
    "T7": {"iata": "T7", "name": "Twin Jet", "country": "France"},
    "9I": {"iata": "9I", "name": "Thai Sky Airlines", "country": "Thailand"},
    "3P": {"iata": "3P", "name": "Tiara Air", "country": "Aruba"},
    "TI": {"iata": "TI", "name": "Tol-Air Services", "country": "United States"},
    "BY": {"iata": "BY", "name": "Thomsonfly", "country": "United Kingdom"},
    "PM": {"iata": "PM", "name": "Tropic Air", "country": "Belize"},
    "QT": {"iata": "QT", "name": "TAMPA", "country": "Colombia"},
    "GE": {"iata": "GE", "name": "TransAsia Airways", "country": "Taiwan"},
    "HV": {"iata": "HV", "name": "Transavia Holland", "country": "Netherlands"},
    "VR": {"iata": "VR", "name": "TACV", "country": "Portugal"},
    "T9": {"iata": "T9", "name": "TransMeridian Airlines", "country": "United States"},
    "9T": {"iata": "9T", "name": "Transwest Air", "country": "Canada"},
    "UN": {"iata": "UN", "name": "Transaero Airlines", "country": "Russia"},
    "T5": {"iata": "T5", "name": "Turkmenistan Airlines", "country": "Turkmenistan"},
    "UG": {"iata": "UG", "name": "Tuninter", "country": "Tunisia"},
    "T6": {"iata": "T6", "name": "Tavrey Airlines", "country": "Ukraine"},
    "TW": {"iata": "TW", "name": "Trans World Airlines", "country": "United States"},
    "6B": {"iata": "6B", "name": "TUIfly Nordic", "country": "Sweden"},
    "DT": {"iata": "DT", "name": "TAAG Angola Airlines", "country": "Angola"},
    "SF": {"iata": "SF", "name": "Tassili Airlines", "country": "Algeria"},
    "PZ": {"iata": "PZ", "name": "TAM Mercosur", "country": "Paraguay"},
    "AX": {"iata": "AX", "name": "Trans States Airlines", "country": "United States"},
    "1E": {"iata": "1E", "name": "Travelsky Technology", "country": "China"},
    "2H": {"iata": "2H", "name": "Thalys", "country": "Belgium"},
    "1L": {"iata": "1L", "name": "Open Skies Consultative Commission", "country": "United States"},
    "RO": {"iata": "RO", "name": "Tarom", "country": "Romania"},
    "3T": {"iata": "3T", "name": "Turan Air", "country": "Azerbaijan"},
    "8R": {"iata": "8R", "name": "TRIP Linhas A", "country": "Brazil"},
    "U5": {"iata": "U5", "name": "USA3000 Airlines", "country": "United States"},
    "UA": {"iata": "UA", "name": "United Airlines", "country": "United States"},
    "U6": {"iata": "U6", "name": "Ural Airlines", "country": "Russia"},
    "UF": {"iata": "UF", "name": "UM Airlines", "country": "Ukraine"},
    "6Z": {"iata": "6Z", "name": "Ukrainian Cargo Airways", "country": "Ukraine"},
    "5X": {"iata": "5X", "name": "United Parcel Service", "country": "United States"},
    "US": {"iata": "US", "name": "US Airways", "country": "United States"},
    "UT": {"iata": "UT", "name": "UTair Aviation", "country": "Russia"},
    "HY": {"iata": "HY", "name": "Uzbekistan Airways", "country": "Uzbekistan"},
    "UH": {"iata": "UH", "name": "US Helicopter Corporation", "country": "United States"},
    "VA": {"iata": "VA", "name": "V Australia Airlines", "country": "Australia"},
    "VF": {"iata": "VF", "name": "Valuair", "country": "Singapore"},
    "VN": {"iata": "VN", "name": "Vietnam Airlines", "country": "Vietnam"},
    "NN": {"iata": "NN", "name": "VIM Airlines", "country": "Russia"},
    "2R": {"iata": "2R", "name": "VIA Rail Canada", "country": "Canada"},
    "Y4": {"iata": "Y4", "name": "Volaris", "country": "Mexico"},
    "VI": {"iata": "VI", "name": "Volga-Dnepr Airlines", "country": "Russia"},
    "VX": {"iata": "VX", "name": "Virgin America", "country": "United States"},
    "TV": {"iata": "TV", "name": "Virgin Express", "country": "Belgium"},
    "VK": {"iata": "VK", "name": "Virgin Nigeria Airways", "country": "Nigeria"},
    "VS": {"iata": "VS", "name": "Virgin Atlantic Airways", "country": "United Kingdom"},
    "ZG": {"iata": "ZG", "name": "Viva Macau", "country": "Macao"},
    "XF": {"iata": "XF", "name": "Vladivostok Air", "country": "Russia"},
    "LC": {"iata": "LC", "name": "Varig Log", "country": "Brazil"},
    "VM": {"iata": "VM", "name": "Viaggio Air", "country": "Bulgaria"},
    "RG": {"iata": "RG", "name": "VRG Linhas Aereas", "country": "Brazil"},
    "VP": {"iata": "VP", "name": "VASP", "country": "Brazil"},
    "VG": {"iata": "VG", "name": "VLM Airlines", "country": "Belgium"},
    "7W": {"iata": "7W", "name": "Wayraper", "country": "Peru"},
    "WJ": {"iata": "WJ", "name": "WebJet Linhas A", "country": "Brazil"},
    "2W": {"iata": "2W", "name": "Welcome Air", "country": "Austria"},
    "8O": {"iata": "8O", "name": "West Coast Air", "country": "Canada"},
    "WS": {"iata": "WS", "name": "WestJet", "country": "Canada"},
    "WF": {"iata": "WF", "name": "Widerøe", "country": "Norway"},
    "IV": {"iata": "IV", "name": "Wind Jet", "country": "Italy"},
    "W6": {"iata": "W6", "name": "Wizz Air", "country": "Hungary"},
    "8Z": {"iata": "8Z", "name": "Wizz Air Hungary", "country": "Bulgaria"},
    "WO": {"iata": "WO", "name": "World Airways", "country": "United States"},
    "1P": {"iata": "1P", "name": "Worldspan", "country": "United States"},
    "SE": {"iata": "SE", "name": "XL Airways France", "country": "France"},
    "MF": {"iata": "MF", "name": "Xiamen Airlines", "country": "China"},
    "XP": {"iata": "XP", "name": "Xtra Airways", "country": "United States"},
    "YL": {"iata": "YL", "name": "Yamal Airlines", "country": "Russia"},
    "Y8": {"iata": "Y8", "name": "Yangtze River Express", "country": "China"},
    "IY": {"iata": "IY", "name": "Yemenia", "country": "Yemen"},
    "Q3": {"iata": "Q3", "name": "Zambian Airways", "country": "Zambia"},
    "3J": {"iata": "3J", "name": "Zip", "country": "Canada"},
    "C4": {"iata": "C4", "name": "Zimex Aviation", "country": "Switzerland"},
    "Z4": {"iata": "Z4", "name": "Zoom Airlines", "country": "Canada"},
    "Y0": {"iata": "Y0", "name": "Yellow Air Taxi", "country": "United States"},
    "6T": {"iata": "6T", "name": "Air Mandalay", "country": "Burma"},
    "TB": {"iata": "TB", "name": "TUI Airlines Belgium", "country": "Belgium"},
    "XW": {"iata": "XW", "name": "Sky Express", "country": "Russia"},
    "BU": {"iata": "BU", "name": "Braathens", "country": "Norway"},
    "GH": {"iata": "GH", "name": "Globus", "country": "Russia"},
    "9Y": {"iata": "9Y", "name": "Air Kazakhstan", "country": "Kazakhstan"},
    "JD": {"iata": "JD", "name": "Japan Air System", "country": "Japan"},
    "ZQ": {"iata": "ZQ", "name": "Annsett New Zealand (NZA)", "country": "New Zealand"},
    "DS": {"iata": "DS", "name": "EasyJet (DS)", "country": "Switzerland"},
    "2I": {"iata": "2I", "name": "Star Peru (2I)", "country": "Peru"},
    "KW": {"iata": "KW", "name": "Carnival Air Lines", "country": "United States"},
    "4H": {"iata": "4H", "name": "United Airways", "country": "Bangladesh"},
    "M8": {"iata": "M8", "name": "Trans Maldivian Airways", "country": "Maldives"},
    "5H": {"iata": "5H", "name": "Fly540", "country": "Kenya"},
    "WP": {"iata": "WP", "name": "Island Air (WP)", "country": "United States"},
    "OG": {"iata": "OG", "name": "1-2-go", "country": "Thailand"},
    "B7": {"iata": "B7", "name": "Uni Air", "country": "Taiwan"},
    "YD": {"iata": "YD", "name": "Gomelavia", "country": "Belarus"},
    "WZ": {"iata": "WZ", "name": "Red Wings", "country": "Russia"},
    "11": {"iata": "11", "name": "TUIfly (X3)", "country": "Germany"},
    "FU": {"iata": "FU", "name": "Felix Airways", "country": "Yemen"},
    "K1": {"iata": "K1", "name": "Kostromskie avialinii", "country": "Russia"},
    "XX": {"iata": "XX", "name": "Greenfly", "country": "Spain"},
    "7J": {"iata": "7J", "name": "Tajik Air", "country": "Tajikistan"},
    "TM": {"iata": "TM", "name": "Air Mozambique", "country": "Mozambique"},
    "VH": {"iata": "VH", "name": "Virgin Pacific", "country": "Fiji"},
    "Z2": {"iata": "Z2", "name": "Zest Air", "country": "Philippines"},
    "3O": {"iata": "3O", "name": "Air Arabia Maroc", "country": "Morocco"},
    "B1": {"iata": "B1", "name": "Baltic Air lines", "country": "Latvia"},
    "YC": {"iata": "YC", "name": "Ciel Canadien", "country": "Canada"},
    "3I": {"iata": "3I", "name": "Air Comet Chile", "country": "Chile"},
    "DN": {"iata": "DN", "name": "Voronezhskie Airlanes", "country": "Russia"},
    "IL": {"iata": "IL", "name": "Illinois Airways", "country": "United States"},
    "SZ": {"iata": "SZ", "name": "Salzburg arrows", "country": "Austria"},
    "KT": {"iata": "KT", "name": "California Western", "country": "United States"},
    "ZZ": {"iata": "ZZ", "name": "Zz", "country": "Belgium"},
    "A1": {"iata": "A1", "name": "Atifly", "country": "United States"},
    "CB": {"iata": "CB", "name": "Suckling Airways", "country": "United Kingdom"},
    "RY": {"iata": "RY", "name": "Reno Sky", "country": "United States"},
    "99": {"iata": "99", "name": "Ciao Air", "country": "Italy"},
    "VB": {"iata": "VB", "name": "Birmingham European", "country": "United Kingdom"},
    "5P": {"iata": "5P", "name": "Pal airlines", "country": "Chile"},
    "C1": {"iata": "C1", "name": "CanXpress", "country": "Canada"},
    "C2": {"iata": "C2", "name": "CanXplorer", "country": "Canada"},
    "QA": {"iata": "QA", "name": "Click (Mexicana)", "country": "Mexico"},
    "W1": {"iata": "W1", "name": "World Experience Airline", "country": "Canada"},
    "3E": {"iata": "3E", "name": "Air Choice One", "country": "United States"},
    "KN": {"iata": "KN", "name": "China United", "country": "China"},
    "4Q": {"iata": "4Q", "name": "Safi Airlines", "country": "Afghanistan"},
    "01": {"iata": "01", "name": "Bobb Air Freight", "country": "Germany"},
    "6D": {"iata": "6D", "name": "Pelita", "country": "Indonesia"},
    "J5": {"iata": "J5", "name": "Alaska Seaplane Service", "country": "United States"},
    "T8": {"iata": "T8", "name": "TAN", "country": "Argentina"},
    "T0": {"iata": "T0", "name": "TACA Peru", "country": "Peru"},
    "7Q": {"iata": "7Q", "name": "Pan Am World Airways Dominicana", "country": "Dominican Republic"},
    "V6": {"iata": "V6", "name": "VIP Ecuador", "country": "Ecuador"},
    "ЯП": {"iata": "ЯП", "name": "Polar Airlines", "country": "Russia"},
    "OC": {"iata": "OC", "name": "Catovair", "country": "Mauritius"},
    "7Z": {"iata": "7Z", "name": "Halcyonair", "country": "Cape Verde"},
    "4P": {"iata": "4P", "name": "Business Aviation", "country": "Congo (Kinshasa)"},
    "UJ": {"iata": "UJ", "name": "AlMasria Universal Airlines", "country": "Egypt"},
    "6Y": {"iata": "6Y", "name": "SmartLynx Airlines", "country": "Latvia"},
    "K7": {"iata": "K7", "name": "KoralBlue Airlines", "country": "Egypt"},
    "7Y": {"iata": "7Y", "name": "Med Airways", "country": "Lebanon"},
    "RL": {"iata": "RL", "name": "Royal Falcon", "country": "Jordan"},
    "4L": {"iata": "4L", "name": "Euroline", "country": "Georgia"},
    "ZF": {"iata": "ZF", "name": "Athens Airways", "country": "Greece"},
    "VQ": {"iata": "VQ", "name": "Viking Hellas", "country": "Greece"},
    "DZ": {"iata": "DZ", "name": "Starline.kz", "country": "Kazakhstan"},
    "OQ": {"iata": "OQ", "name": "Chongqing Airlines", "country": "China"},
    "PN": {"iata": "PN", "name": "West Air China", "country": "China"},
    "Y7": {"iata": "Y7", "name": "NordStar Airlines", "country": "Russia"},
    "9H": {"iata": "9H", "name": "MDLR Airlines", "country": "India"},
    "Q2": {"iata": "Q2", "name": "Maldivian", "country": "Maldives"},
    "XN": {"iata": "XN", "name": "Xpressair", "country": "Indonesia"},
    "5E": {"iata": "5E", "name": "SGA Airlines", "country": "Thailand"},
    "F8": {"iata": "F8", "name": "Air2there", "country": "New Zealand"},
    "WQ": {"iata": "WQ", "name": "PanAm World Airways", "country": "United States"},
    "YY": {"iata": "YY", "name": "Virginwings", "country": "Germany"},
    "WU": {"iata": "WU", "name": "Wizz Air Ukraine", "country": "Ukraine"},
    "47": {"iata": "47", "name": "88", "country": "Cyprus"},
    "H3": {"iata": "H3", "name": "THREE", "country": "China"},
    "69": {"iata": "69", "name": "Royal European Airlines", "country": "United Kingdom"},
    "&T": {"iata": "&T", "name": "Tom\\'s & co airliners", "country": "France"},
    "X1": {"iata": "X1", "name": "Nik Airways", "country": "Saudi Arabia"},
    "XZ": {"iata": "XZ", "name": "Congo Express", "country": "Congo (Kinshasa)"},
    "FZ": {"iata": "FZ", "name": "Fly Dubai", "country": "United Arab Emirates"},
    "D1": {"iata": "D1", "name": "Domenican Airlines", "country": "Dominican Republic"},
    "9A": {"iata": "9A", "name": "Air Atlantic", "country": "Canada"},
    "YZ": {"iata": "YZ", "name": "LSM AIRLINES ", "country": "Russia"},
    "YP": {"iata": "YP", "name": "Aero Lloyd (YP)", "country": "Germany"},
    "UR": {"iata": "UR", "name": "UTair-Express", "country": "Russia"},
    "G5": {"iata": "G5", "name": "Huaxia", "country": "China"},
    "N1": {"iata": "N1", "name": "N1", "country": "Peru"},
    "4Z": {"iata": "4Z", "name": "Airlink (SAA)", "country": "South Africa"},
    "3B": {"iata": "3B", "name": "JobAir", "country": "Czech Republic"},
    "OD": {"iata": "OD","imgcode" : "MR", "name": "Malindo Air", "country": "Malaysia"},
    "9C": {"iata": "9C", "name": "China SSS", "country": "China"},
    "NJ": {"iata": "NJ", "name": "Nihon.jet", "country": "Japan"},
    "TJ": {"iata": "TJ", "name": "Transportes Aéreos Nacionales de Selva", "country": "Peru"},
    "Z6": {"iata": "Z6", "name": "ZABAIKAL AIRLINES", "country": "Russia"},
    "Y1": {"iata": "Y1", "name": "Yellowstone Club Private Shuttle", "country": "United States"},
    "NS": {"iata": "NS", "name": "Caucasus Airlines", "country": "Georgia"},
    "S1": {"iata": "S1", "name": "Serbian Airlines", "country": "Serbia"},
    "WM": {"iata": "WM", "name": "Windward Islands Airways", "country": "Netherlands Antilles"},
    "YO": {"iata": "YO", "name": "TransHolding System", "country": "Brazil"},
    "F1": {"iata": "F1", "name": "Fly Brasil", "country": "Brazil"},
    "3F": {"iata": "3F", "name": "Fly Colombia ( Interliging Flights )", "country": "Colombia"},
    "МИ": {"iata": "МИ", "name": "KMV", "country": "Russia"},
    "N0": {"iata": "N0", "name": "Norte Lineas Aereas", "country": "Argentina"},
    "W7": {"iata": "W7", "name": "Austral Brasil", "country": "Brazil"},
    "YI": {"iata": "YI", "name": "TUR Avrupa Hava YollarÄ±", "country": "Turkey"},
    "L4": {"iata": "L4", "name": "Luchsh Airlines ", "country": "Russia"},
    "7M": {"iata": "7M", "name": "Mongolian International Air Lines ", "country": "Mongolia"},
    "HI": {"iata": "HI", "name": "Papillon Grand Canyon Helicopters", "country": "United States"},
    "XB": {"iata": "XB", "name": "NEXT Brasil", "country": "Brazil"},
    "KH": {"iata": "KH", "name": "Cook Island Air", "country": "Cook Islands"},
    "E1": {"iata": "E1", "name": "Usa Sky Cargo", "country": "United States"},
    "0G": {"iata": "0G", "name": "Sprintair", "country": "Poland"},
    "4X": {"iata": "4X", "name": "Red Jet Mexico", "country": "Mexico"},
    "7H": {"iata": "7H", "name": "Era Alaska", "country": "United States"},
    "H1": {"iata": "H1", "name": "Hankook Air US", "country": "United States"},
    "10": {"iata": "10", "name": "Canadian World", "country": "Canada"},
    "XV": {"iata": "XV", "name": "BVI Airways", "country": "British Virgin Islands"},
    "ZJ": {"iata": "ZJ", "name": "Zambezi Airlines (ZMA)", "country": "Zambia"},
    "YQ": {"iata": "YQ", "name": "Polet Airlines (Priv)", "country": "Russia"},
    "T1": {"iata": "T1", "name": "TROPICAL LINHAS AEREAS", "country": "Brazil"},
    "12": {"iata": "12", "name": "12 North", "country": "India"},
    "L6": {"iata": "L6", "name": "Mauritania Airlines International", "country": "Mauritania"},
    "6F": {"iata": "6F", "name": "MAT Airways", "country": "Macedonia"},
    "OI": {"iata": "OI", "name": "Orchid Airlines", "country": "Australia"},
    "XR": {"iata": "XR", "name": "Skywest Australia", "country": "Australia"},
    "NP": {"iata": "NP", "name": "Nile Air", "country": "Egypt"},
    "0X": {"iata": "0X", "name": "Copenhagen Express", "country": "Denmark"},
    "YR": {"iata": "YR", "name": "SENIC AIRLINES", "country": "United States"},
    "PP": {"iata": "PP", "name": "Air Indus", "country": "Pakistan"},
    "07": {"iata": "07", "name": "Samurai Airlines", "country": "Pakistan"},
    "00": {"iata": "00", "name": "AirOne Continental", "country": "Slovakia"},
    "U1": {"iata": "U1", "name": "AirOne Polska", "country": "Poland"},
    "DF": {"iata": "DF", "name": "Michael Airlines", "country": "Puerto Rico"},
    "ZC": {"iata": "ZC", "name": "Korongo Airlines", "country": "Congo (Kinshasa)"},
    "I5": {"iata": "I5", "name": "Indonesia Sky", "country": "Indonesia"},
    "9P": {"iata": "9P", "name": "Pelangi ", "country": "Malaysia"},
    "B0": {"iata": "B0", "name": "Aws express", "country": "United States"},
    "76": {"iata": "76", "name": "Southjet", "country": "United States"},
    "77": {"iata": "77", "name": "Southjet connect", "country": "United States"},
    "78": {"iata": "78", "name": "Southjet cargo", "country": "United States"},
    "I2": {"iata": "I2", "name": "Iberia Express", "country": "Spain"},
    "4O": {"iata": "4O", "name": "Interjet (ABC Aerolineas)", "country": "Mexico"},
    "ZN": {"iata": "ZN", "name": "Zenith International Airline", "country": "Thailand"},
    "O1": {"iata": "O1", "name": "Orbit Airlines Azerbaijan", "country": "Azerbaijan"},
    "P4": {"iata": "P4", "name": "Patriot Airways", "country": "United States"},
    "5Q": {"iata": "5Q", "name": "BQB Lineas Aereas", "country": "Uruguay"},
    "YE": {"iata": "YE", "name": "Yellowtail", "country": "United States"},
    "YH": {"iata": "YH", "name": "Yangon Airways Ltd.", "country": "Burma"},
    "WL": {"iata": "WL", "name": "CheapFlyingInternational", "country": "France"},
    "24": {"iata": "24", "name": "Euro Jet", "country": "Germany"},
    "9F": {"iata": "9F", "name": "Tramm Airlines", "country": "Netherlands Antilles"},
    "Z9": {"iata": "Z9", "name": "Flightlink Tanzania", "country": "Tanzania"},
    "I8": {"iata": "I8", "name": "IzAvia", "country": "Russia"},
    "M1": {"iata": "M1", "name": "Maryland Air", "country": "United States"},
    "7I": {"iata": "7I", "name": "Insel Air (7I/INC) (Priv)", "country": "Netherlands Antilles"},
    "ZM": {"iata": "ZM", "name": "Apache Air", "country": "United States"},
    "13": {"iata": "13", "name": "Eastern Atlantic Virtual Airlines", "country": "United States"},
    "QG": {"iata": "QG", "name": "Citilink Indonesia", "country": "Indonesia"},
    "GU": {"iata": "GU", "name": "Gulisano airways", "country": "Italy"},
    "XA": {"iata": "XA", "name": "XAIR USA", "country": "United States"},
    "RN": {"iata": "RN", "name": "Rainbow Air (RAI)", "country": "United States"},
    "RM": {"iata": "RM", "name": "Rainbow Air US", "country": "United States"},
    "9N": {"iata": "9N", "name": "Regional Air Iceland", "country": "Iceland"},
    "8K": {"iata": "8K", "name": "Voestar", "country": "Brazil"},
    "2X": {"iata": "2X", "name": "Regionalia Uruguay", "country": "Uruguay"},
    "9J": {"iata": "9J", "name": "Regionalia Chile", "country": "Chile"},
    "6C": {"iata": "6C", "name": "Vuela Cuba", "country": "Cuba"},
    "88": {"iata": "88", "name": "All Australia", "country": "Australia"},
    "2Y": {"iata": "2Y", "name": "My Indo Airlines", "country": "Indonesia"},
    "O3": {"iata": "O3", "name": "SF Airlines", "country": "China"},
}
